### ISSUE TITLE
Getting setup is maybe harder than it should be?

### ISSUE THREAD

**Issue by phildini** [forumone/peacecorps-site#352]
Hello! I have trying to make my way through some of the 'help wanted' issues, and have been unable to get a working devenv setup. It seems like the development flow is better optimized for linux, and I imagine that's where the app is being deployed, so would the maintainers of this project be adverse to me setting up a Vagrantfile and shell script for bootstrapping a devenv?

**Comment by seanherron** [comment]
Thanks for reaching out, @phildini! We'd definitely be interested in a pull request for a working Vagrant development environment and appreciate your willingness to help. If you're looking for some inspiration, here's what I'm using in a different django project elsewhere in 18F:

https://github.com/18F/tock/blob/master/provision/dev/bootstrap.sh
https://github.com/18F/tock/blob/master/Vagrantfile

**Comment by cmc333333** [comment]
And of course, if you're having any specific problems, post here and we'll try to work them out and update the README.

**Comment by phildini** [comment]
I'm going to try and port the Vagrantfile soon, but for the record here's what I went through before giving up installing on a mac.
1. Installed python3 through homebrew.
2. Installed mkvirtualenv
3. ran `mkvirtualenv --python=/usr/local/bin/Python3 peacecorps-site`
4. mkvirtualenv failed with `OSError: [Errno 62] Too many levels of symbolic links`
5. Tried pyenv method, same mkvirtualenv problem.
6. Used `pyvenv` to create a virtualenv in the peacecorps-site directory - successfully created
7. Activated virtualenv, tried to install requirements.txt, got the following error:

```
    In file included from src/_pylibmcmodule.c:34:
    src/_pylibmcmodule.h:42:10: fatal error: 'libmemcached/memcached.h' file not found
    #include <libmemcached/memcached.h>
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
    Cleaning up...
```

**Comment by cmc333333** [comment]
Good point. We use the memcached library (specifically, the production settings use this). In debian/ubuntu land, this would be an `apt-get install libmemcached-dev`. I assume homebrew is similar?

**Comment by phildini** [comment]
The saga in getting setup continues. Is it helpful to continue documenting issues here or should I move on?

**Comment by cmc333333** [comment]
Closing, per comments in #358
