### ISSUE TITLE
No Files Email Alert Still Running 

### ISSUE THREAD

**Issue by kgallagher** [forumone/peacecorps-site#378]
Hi Chris,

At 2:13 today we got one of the emails alerting us that files haven't been delivered (email pasted below). These are the emails that 18F set up  (not the other ones we discovered that OCIO was generating). Is the Odyssey connection still running ok? If so, can we please turn these off?

Thanks,
Kelley

cc: @jacobgodin 

-----Original Message-----
From: noreply@peacecorps.gov [mailto:noreply@peacecorps.gov] 
Sent: Wednesday, September 30, 2015 2:13 PM
To: christopher.lubinski@gsa.gov; Gallagher, Kelley; Shami, Saad; Serebrennikov, Mikhail; Trajkovic, Nicolas
Subject: No file in 24 hours

The latest files (files deleted every 7 days):

/home/filetransfer/incoming/fund_data_201509010700.csv UTC:Sep 1 11:00 /home/filetransfer/incoming/fund_data_201509010800.csv UTC:Sep 1 12:00 /home/filetransfer/incoming/fund_data_201509010900.csv UTC:Sep 1 13:00 /home/filetransfer/incoming/fund_data_201509011000.csv UTC:Sep 1 14:00 /home/filetransfer/incoming/fund_data_201509011100.csv UTC:Sep 1 15:00 /home/filetransfer/incoming/fund_data_201509011200.csv UTC:Sep 1 16:00 /home/filetransfer/incoming/fund_data_201509011300.csv UTC:Sep 1 17:00 /home/filetransfer/incoming/fund_data_201509011400.csv UTC:Sep 1 18:00 /home/filetransfer/incoming/fund_data_201509011500.csv UTC:Sep 1 19:00 /home/filetransfer/incoming/fund_data_201509011600.csv UTC:Sep 1 20:00 /home/filetransfer/incoming/fund_data_201509011700.csv UTC:Sep 1 21:00 /home/filetransfer/incoming/fund_data_201509011800.csv UTC:Sep 1 22:00 /home/filetransfer/incoming/fund_data_201509011900.csv UTC:Sep 1 23:00 /home/filetransfer/incoming/fund_data_201509012000.csv UTC:Sep 2 00:00 /home/filetransfer/incoming/fund_data_201509012100.csv UTC:Sep 2 01:00 /home/filetransfer/incoming/fund_data_201509020700.csv UTC:Sep 2 11:00 /home/filetransfer/incoming/fund_data_201509020800.csv UTC:Sep 2 12:00 /home/filetransfer/incoming/fund_data_201509020900.csv UTC:Sep 2 13:00 /home/filetransfer/incoming/fund_data_201509020935.csv UTC:Sep 2 13:35 /home/filetransfer/incoming/fund_data_201509021035.csv UTC:Sep 2 14:35 /home/filetransfer/incoming/fund_data_201509021135.csv UTC:Sep 2 15:35 /home/filetransfer/incoming/fund_data_201509021235.csv UTC:Sep 2 16:35 /home/filetransfer/incoming/fund_data_201509021335.csv UTC:Sep 2 17:35 /home/filetransfer/incoming/fund_data_201509021435.csv UTC:Sep 2 18:35 /home/filetransfer/incoming/fund_data_201509021535.csv UTC:Sep 2 19:35 /home/filetransfer/incoming/fund_data_201509021635.csv UTC:Sep 2 20:35 /home/filetransfer/incoming/fund_data_201509021735.csv UTC:Sep 2 21:35 /home/filetransfer/incoming/fund_data_201509021835.csv UTC:Sep 2 22:35 /home/filetransfer/incoming/fund_data_201509021935.csv UTC:Sep 2 23:35 /home/filetransfer/incoming/fund_data_201509022035.csv UTC:Sep 3 00:35 /home/filetransfer/incoming/fund_data_201509030700.csv UTC:Sep 3 11:00 /home/filetransfer/incoming/fund_data_201509030800.csv UTC:Sep 3 12:00 /home/filetransfer/incoming/fund_data_201509030900.csv UTC:Sep 3 13:00 /home/filetransfer/incoming/fund_data_201509031000.csv UTC:Sep 3 14:00 /home/filetransfer/incoming/fund_data_201509031100.csv UTC:Sep 3 15:00 /home/filetransfer/incoming/fund_data_201509031200.csv UTC:Sep 3 16:00 /home/filetransfer/incoming/fund_data_201509031300.csv UTC:Sep 3 17:00 /home/filetransfer/incoming/fund_data_201509031400.csv UTC:Sep 3 18:00 /home/filetransfer/incoming/fund_data_201509031500.csv UTC:Sep 3 19:00 /home/filetransfer/incoming/fund_data_201509031600.csv UTC:Sep 3 20:00 /home/filetransfer/incoming/fund_data_201509031700.csv UTC:Sep 3 21:00 /home/filetransfer/incoming/fund_data_201509031800.csv UTC:Sep 3 22:00 /home/filetransfer/incoming/fund_data_201509031900.csv UTC:Sep 3 23:00 /home/filetransfer/incoming/fund_data_201509032000.csv UTC:Sep 4 00:00 /home/filetransfer/incoming/fund_data_201509032100.csv UTC:Sep 4 01:00 /home/filetransfer/incoming/fund_data_201509040700.csv UTC:Sep 4 11:00 /home/filetransfer/incoming/fund_data_201509040800.csv UTC:Sep 4 12:00 /home/filetransfer/incoming/fund_data_201509040900.csv UTC:Sep 4 13:00 /home/filetransfer/incoming/fund_data_201509041000.csv UTC:Sep 4 14:00 /home/filetransfer/incoming/fund_data_201509041100.csv UTC:Sep 4 15:00 /home/filetransfer/incoming/fund_data_201509041200.csv UTC:Sep 4 16:00 /home/filetransfer/incoming/fund_data_201509041300.csv UTC:Sep 4 17:00 /home/filetransfer/incoming/fund_data_201509041400.csv UTC:Sep 4 18:00 /home/filetransfer/incoming/fund_data_201509041500.csv UTC:Sep 4 19:00 /home/filetransfer/incoming/fund_data_201509041600.csv UTC:Sep 4 20:00 /home/filetransfer/incoming/fund_data_201509041700.csv UTC:Sep 4 21:00 /home/filetransfer/incoming/fund_data_201509041800.csv UTC:Sep 4 22:00 /home/filetransfer/incoming/fund_data_201509041900.csv UTC:Sep 4 23:00 /home/filetransfer/incoming/fund_data_201509042000.csv UTC:Sep 5 00:00 /home/filetransfer/incoming/fund_data_201509042100.csv UTC:Sep 5 01:00 /home/filetransfer/incoming/fund_data_201509050700.csv UTC:Sep 5 11:00 /home/filetransfer/incoming/fund_data_201509050800.csv UTC:Sep 5 12:00 /home/filetransfer/incoming/fund_data_201509050900.csv UTC:Sep 5 13:00 /home/filetransfer/incoming/fund_data_201509051000.csv UTC:Sep 5 14:00 /home/filetransfer/incoming/fund_data_201509051100.csv UTC:Sep 5 15:00 /home/filetransfer/incoming/fund_data_201509051200.csv UTC:Sep 5 16:00 /home/filetransfer/incoming/fund_data_201509051300.csv UTC:Sep 5 17:00 /home/filetransfer/incoming/fund_data_201509051400.csv UTC:Sep 5 18:00 /home/filetransfer/incoming/fund_data_201509051500.csv UTC:Sep 5 19:00 /home/filetransfer/incoming/fund_data_201509051600.csv UTC:Sep 5 20:00 /home/filetransfer/incoming/fund_data_201509051700.csv UTC:Sep 5 21:00 /home/filetransfer/incoming/fund_data_201509051800.csv UTC:Sep 5 22:00 /home/filetransfer/incoming/fund_data_201509051900.csv UTC:Sep 5 23:00 /home/filetransfer/incoming/fund_data_201509052000.csv UTC:Sep 6 00:00 /home/filetransfer/incoming/fund_data_201509052100.csv UTC:Sep 6 01:00 /home/filetransfer/incoming/fund_data_201509070700.csv UTC:Sep 7 11:00 /home/filetransfer/incoming/fund_data_201509070800.csv UTC:Sep 7 12:00 /home/filetransfer/incoming/fund_data_201509070900.csv UTC:Sep 7 13:00 /home/filetransfer/incoming/fund_data_201509071000.csv UTC:Sep 7 14:00 /home/filetransfer/incoming/fund_data_201509071100.csv UTC:Sep 7 15:00 /home/filetransfer/incoming/fund_data_201509071200.csv UTC:Sep 7 16:00 /home/filetransfer/incoming/fund_data_201509071300.csv UTC:Sep 7 17:00 /home/filetransfer/incoming/fund_data_201509071400.csv UTC:Sep 7 18:00 /home/filetransfer/incoming/fund_data_201509071500.csv UTC:Sep 7 19:00 /home/filetransfer/incoming/fund_data_201509071600.csv UTC:Sep 7 20:00 /home/filetransfer/incoming/fund_data_201509071700.csv UTC:Sep 7 21:00 /home/filetransfer/incoming/fund_data_201509071800.csv UTC:Sep 7 22:00 /home/filetransfer/incoming/fund_data_201509071900.csv UTC:Sep 7 23:00 /home/filetransfer/incoming/fund_data_201509072000.csv UTC:Sep 8 00:00 /home/filetransfer/incoming/fund_data_201509072100.csv UTC:Sep 8 01:00 /home/filetransfer/incoming/fund_data_201509080700.csv UTC:Sep 8 11:00 /home/filetransfer/incoming/fund_data_201509080800.csv UTC:Sep 8 12:00 /home/filetransfer/incoming/fund_data_201509080900.csv UTC:Sep 8 13:00 /home/filetransfer/incoming/fund_data_201509081000.csv UTC:Sep 8 14:00 /home/filetransfer/incoming/fund_data_201509081100.csv UTC:Sep 8 15:00 /home/filetransfer/incoming/fund_data_201509081200.csv UTC:Sep 8 16:00 /home/filetransfer/incoming/fund_data_201509081300.csv UTC:Sep 8 17:00 /home/filetransfer/incoming/fund_data_201509081400.csv UTC:Sep 8 18:00 /home/filetransfer/incoming/fund_data_201509081500.csv UTC:Sep 8 19:00 /home/filetransfer/incoming/fund_data_201509081600.csv UTC:Sep 8 20:00 /home/filetransfer/incoming/fund_data_201509081700.csv UTC:Sep 8 21:00 /home/filetransfer/incoming/fund_data_201509081800.csv UTC:Sep 8 22:00 /home/filetransfer/incoming/fund_data_201509081900.csv UTC:Sep 8 23:00 /home/filetransfer/incoming/fund_data_201509082000.csv UTC:Sep 9 00:00 /home/filetransfer/incoming/fund_data_201509082100.csv UTC:Sep 9 01:00 /home/filetransfer/incoming/fund_data_201509090700.csv UTC:Sep 9 11:00 /home/filetransfer/incoming/fund_data_201509090800.csv UTC:Sep 9 12:00 /home/filetransfer/incoming/fund_data_201509090900.csv UTC:Sep 9 13:00 /home/filetransfer/incoming/fund_data_201509091000.csv UTC:Sep 9 14:00 /home/filetransfer/incoming/fund_data_201509091100.csv UTC:Sep 9 15:00 /home/filetransfer/incoming/fund_data_201509091200.csv UTC:Sep 9 16:00 /home/filetransfer/incoming/fund_data_201509091300.csv UTC:Sep 9 17:00 /home/filetransfer/incoming/fund_data_201509091400.csv UTC:Sep 9 18:00 /home/filetransfer/incoming/fund_data_201509091500.csv UTC:Sep 9 19:00 /home/filetransfer/incoming/fund_data_201509091600.csv UTC:Sep 9 20:00 /home/filetransfer/incoming/fund_data_201509091700.csv UTC:Sep 9 21:00 /home/filetransfer/incoming/fund_data_201509091800.csv UTC:Sep 9 22:00 /home/filetransfer/incoming/fund_data_201509091900.csv UTC:Sep 9 23:00 /home/filetransfer/incoming/fund_data_201509092000.csv UTC:Sep 10 00:00 /home/filetransfer/incoming/fund_data_201509092100.csv UTC:Sep 10 01:00 /home/filetransfer/incoming/fund_data_201509100700.csv UTC:Sep 10 11:00 /home/filetransfer/incoming/fund_data_201509100800.csv UTC:Sep 10 12:00 /home/filetransfer/incoming/fund_data_201509100900.csv UTC:Sep 10 13:00 /home/filetransfer/incoming/fund_data_201509101000.csv UTC:Sep 10 14:00 /home/filetransfer/incoming/fund_data_201509101200.csv UTC:Sep 10 16:00 /home/filetransfer/incoming/fund_data_201509101300.csv UTC:Sep 10 17:00 /home/filetransfer/incoming/fund_data_201509101400.csv UTC:Sep 10 18:00 /home/filetransfer/incoming/fund_data_201509101500.csv UTC:Sep 10 19:00 /home/filetransfer/incoming/fund_data_201509101600.csv UTC:Sep 10 20:00 /home/filetransfer/incoming/fund_data_201509101700.csv UTC:Sep 10 21:00 /home/filetransfer/incoming/fund_data_201509101800.csv UTC:Sep 10 22:00 /home/filetransfer/incoming/fund_data_201509101900.csv UTC:Sep 10 23:00 /home/filetransfer/incoming/fund_data_201509102000.csv UTC:Sep 11 00:00 /home/filetransfer/incoming/fund_data_201509102100.csv UTC:Sep 11 01:00 /home/filetransfer/incoming/fund_data_201509110700.csv UTC:Sep 11 11:00 /home/filetransfer/incoming/fund_data_201509110800.csv UTC:Sep 11 12:00 /home/filetransfer/incoming/fund_data_201509110900.csv UTC:Sep 11 13:00 /home/filetransfer/incoming/fund_data_201509111000.csv UTC:Sep 11 14:00 /home/filetransfer/incoming/fund_data_201509111100.csv UTC:Sep 11 15:00 /home/filetransfer/incoming/fund_data_201509111200.csv UTC:Sep 11 16:00 /home/filetransfer/incoming/fund_data_201509111300.csv UTC:Sep 11 17:00 /home/filetransfer/incoming/fund_data_201509111400.csv UTC:Sep 11 18:00 /home/filetransfer/incoming/fund_data_201509111500.csv UTC:Sep 11 19:00 /home/filetransfer/incoming/fund_data_201509111600.csv UTC:Sep 11 20:00 /home/filetransfer/incoming/fund_data_201509111700.csv UTC:Sep 11 21:00 /home/filetransfer/incoming/fund_data_201509111800.csv UTC:Sep 11 22:00 /home/filetransfer/incoming/fund_data_201509111900.csv UTC:Sep 11 23:00 /home/filetransfer/incoming/fund_data_201509112000.csv UTC:Sep 12 00:00 /home/filetransfer/incoming/fund_data_201509112100.csv UTC:Sep 12 01:00 /home/filetransfer/incoming/fund_data_201509120700.csv UTC:Sep 12 11:00 /home/filetransfer/incoming/fund_data_201509120800.csv UTC:Sep 12 12:00 /home/filetransfer/incoming/fund_data_201509120900.csv UTC:Sep 12 13:00 /home/filetransfer/incoming/fund_data_201509121000.csv UTC:Sep 12 14:00 /home/filetransfer/incoming/fund_data_201509121100.csv UTC:Sep 12 15:00 /home/filetransfer/incoming/fund_data_201509121200.csv UTC:Sep 12 16:00 /home/filetransfer/incoming/fund_data_201509121300.csv UTC:Sep 12 17:00 /home/filetransfer/incoming/fund_data_201509121400.csv UTC:Sep 12 18:00 /home/filetransfer/incoming/fund_data_201509121500.csv UTC:Sep 12 19:00 /home/filetransfer/incoming/fund_data_201509121600.csv UTC:Sep 12 20:00 /home/filetransfer/incoming/fund_data_201509121700.csv UTC:Sep 12 21:00 /home/filetransfer/incoming/fund_data_201509121800.csv UTC:Sep 12 22:00 /home/filetransfer/incoming/fund_data_201509121900.csv UTC:Sep 12 23:00 /home/filetransfer/incoming/fund_data_201509122000.csv UTC:Sep 13 00:00 /home/filetransfer/incoming/fund_data_201509122100.csv UTC:Sep 13 01:00 /home/filetransfer/incoming/fund_data_201509140700.csv UTC:Sep 14 11:00 /home/filetransfer/incoming/fund_data_201509140800.csv UTC:Sep 14 12:00 /home/filetransfer/incoming/fund_data_201509140900.csv UTC:Sep 14 13:00 /home/filetransfer/incoming/fund_data_201509141000.csv UTC:Sep 14 14:00 /home/filetransfer/incoming/fund_data_201509141100.csv UTC:Sep 14 15:00 /home/filetransfer/incoming/fund_data_201509141200.csv UTC:Sep 14 16:00 /home/filetransfer/incoming/fund_data_201509141230.csv UTC:Sep 14 16:30 /home/filetransfer/incoming/fund_data_201509141330.csv UTC:Sep 14 17:30 /home/filetransfer/incoming/fund_data_201509141430.csv UTC:Sep 14 18:30 /home/filetransfer/incoming/fund_data_201509141630.csv UTC:Sep 14 20:30 /home/filetransfer/incoming/fund_data_201509141730.csv UTC:Sep 14 21:30 /home/filetransfer/incoming/fund_data_201509141830.csv UTC:Sep 14 22:30 /home/filetransfer/incoming/fund_data_201509141930.csv UTC:Sep 14 23:30 /home/filetransfer/incoming/fund_data_201509142030.csv UTC:Sep 15 00:30 /home/filetransfer/incoming/fund_data_201509150700.csv UTC:Sep 15 11:00 /home/filetransfer/incoming/fund_data_201509150800.csv UTC:Sep 15 12:00 /home/filetransfer/incoming/fund_data_201509150900.csv UTC:Sep 15 13:00 /home/filetransfer/incoming/fund_data_201509151000.csv UTC:Sep 15 14:00 /home/filetransfer/incoming/fund_data_201509151100.csv UTC:Sep 15 15:00 /home/filetransfer/incoming/fund_data_201509151200.csv UTC:Sep 15 15:59 /home/filetransfer/incoming/fund_data_201509151300.csv UTC:Sep 15 16:59 /home/filetransfer/incoming/fund_data_201509151400.csv UTC:Sep 15 18:00 /home/filetransfer/incoming/fund_data_201509151500.csv UTC:Sep 15 19:00 /home/filetransfer/incoming/fund_data_201509151600.csv UTC:Sep 15 19:59 /home/filetransfer/incoming/fund_data_201509151700.csv UTC:Sep 15 20:59 /home/filetransfer/incoming/fund_data_201509151800.csv UTC:Sep 15 21:59 /home/filetransfer/incoming/fund_data_201509151900.csv UTC:Sep 15 23:00 /home/filetransfer/incoming/fund_data_201509152000.csv UTC:Sep 15 23:59 /home/filetransfer/incoming/fund_data_201509152100.csv UTC:Sep 16 00:59 /home/filetransfer/incoming/fund_data_201509160700.csv UTC:Sep 16 11:00 /home/filetransfer/incoming/fund_data_201509160800.csv UTC:Sep 16 12:00 /home/filetransfer/incoming/fund_data_201509160900.csv UTC:Sep 16 12:59 /home/filetransfer/incoming/fund_data_201509161000.csv UTC:Sep 16 13:59 /home/filetransfer/incoming/fund_data_201509161100.csv UTC:Sep 16 14:59 /home/filetransfer/incoming/fund_data_201509161200.csv UTC:Sep 16 15:59 /home/filetransfer/incoming/fund_data_201509161300.csv UTC:Sep 16 16:59 /home/filetransfer/incoming/fund_data_201509161400.csv UTC:Sep 16 17:59 /home/filetransfer/incoming/fund_data_201509161500.csv UTC:Sep 16 18:59 /home/filetransfer/incoming/fund_data_201509161600.csv UTC:Sep 16 19:59 /home/filetransfer/incoming/fund_data_201509161700.csv UTC:Sep 16 20:59 /home/filetransfer/incoming/fund_data_201509161800.csv UTC:Sep 16 21:59 /home/filetransfer/incoming/fund_data_201509161900.csv UTC:Sep 16 22:59 /home/filetransfer/incoming/fund_data_201509162000.csv UTC:Sep 16 23:59 /home/filetransfer/incoming/fund_data_201509162100.csv UTC:Sep 17 01:00 /home/filetransfer/incoming/fund_data_201509170700.csv UTC:Sep 17 10:59 /home/filetransfer/incoming/fund_data_201509170800.csv UTC:Sep 17 12:00 /home/filetransfer/incoming/fund_data_201509170900.csv UTC:Sep 17 12:59 /home/filetransfer/incoming/fund_data_201509171000.csv UTC:Sep 17 13:59 /home/filetransfer/incoming/fund_data_201509171100.csv UTC:Sep 17 14:59 /home/filetransfer/incoming/fund_data_201509171200.csv UTC:Sep 17 15:59 /home/filetransfer/incoming/fund_data_201509171300.csv UTC:Sep 17 16:59 /home/filetransfer/incoming/fund_data_201509171400.csv UTC:Sep 17 17:59 /home/filetransfer/incoming/fund_data_201509171500.csv UTC:Sep 17 18:59 /home/filetransfer/incoming/fund_data_201509171600.csv UTC:Sep 17 19:59 /home/filetransfer/incoming/fund_data_201509171700.csv UTC:Sep 17 20:59 /home/filetransfer/incoming/fund_data_201509171800.csv UTC:Sep 17 21:59 /home/filetransfer/incoming/fund_data_201509171900.csv UTC:Sep 17 22:59 /home/filetransfer/incoming/fund_data_201509172000.csv UTC:Sep 17 23:59 /home/filetransfer/incoming/fund_data_201509172100.csv UTC:Sep 18 00:59 /home/filetransfer/incoming/fund_data_201509180700.csv UTC:Sep 18 11:00 /home/filetransfer/incoming/fund_data_201509180800.csv UTC:Sep 18 11:59 /home/filetransfer/incoming/fund_data_201509180900.csv UTC:Sep 18 12:59 /home/filetransfer/incoming/fund_data_201509181000.csv UTC:Sep 18 13:59 /home/filetransfer/incoming/fund_data_201509181100.csv UTC:Sep 18 14:59 /home/filetransfer/incoming/fund_data_201509181200.csv UTC:Sep 18 15:59 /home/filetransfer/incoming/fund_data_201509181300.csv UTC:Sep 18 16:59 /home/filetransfer/incoming/fund_data_201509181400.csv UTC:Sep 18 18:00 /home/filetransfer/incoming/fund_data_201509181500.csv UTC:Sep 18 18:59 /home/filetransfer/incoming/fund_data_201509181600.csv UTC:Sep 18 19:59 /home/filetransfer/incoming/fund_data_201509181700.csv UTC:Sep 18 20:59 /home/filetransfer/incoming/fund_data_201509181800.csv UTC:Sep 18 21:59 /home/filetransfer/incoming/fund_data_201509181900.csv UTC:Sep 18 22:59 /home/filetransfer/incoming/fund_data_201509182000.csv UTC:Sep 18 23:59 /home/filetransfer/incoming/fund_data_201509182100.csv UTC:Sep 19 00:59 /home/filetransfer/incoming/fund_data_201509190700.csv UTC:Sep 19 10:59 /home/filetransfer/incoming/fund_data_201509190800.csv UTC:Sep 19 11:59 /home/filetransfer/incoming/fund_data_201509190900.csv UTC:Sep 19 12:59 /home/filetransfer/incoming/fund_data_201509191000.csv UTC:Sep 19 13:59 /home/filetransfer/incoming/fund_data_201509191100.csv UTC:Sep 19 14:59 /home/filetransfer/incoming/fund_data_201509191200.csv UTC:Sep 19 15:59 /home/filetransfer/incoming/fund_data_201509191300.csv UTC:Sep 19 16:59 /home/filetransfer/incoming/fund_data_201509191400.csv UTC:Sep 19 17:59 /home/filetransfer/incoming/fund_data_201509191500.csv UTC:Sep 19 18:59 /home/filetransfer/incoming/fund_data_201509191600.csv UTC:Sep 19 19:59 /home/filetransfer/incoming/fund_data_201509191700.csv UTC:Sep 19 20:59 /home/filetransfer/incoming/fund_data_201509191800.csv UTC:Sep 19 21:59 /home/filetransfer/incoming/fund_data_201509191900.csv UTC:Sep 19 22:59 /home/filetransfer/incoming/fund_data_201509192000.csv UTC:Sep 19 23:59 /home/filetransfer/incoming/fund_data_201509192100.csv UTC:Sep 20 00:59 /home/filetransfer/incoming/fund_data_201509210700.csv UTC:Sep 21 10:59 /home/filetransfer/incoming/fund_data_201509210800.csv UTC:Sep 21 11:59 /home/filetransfer/incoming/fund_data_201509210900.csv UTC:Sep 21 12:59 /home/filetransfer/incoming/fund_data_201509211000.csv UTC:Sep 21 13:59 /home/filetransfer/incoming/fund_data_201509211100.csv UTC:Sep 21 14:59 /home/filetransfer/incoming/fund_data_201509211200.csv UTC:Sep 21 15:59 /home/filetransfer/incoming/fund_data_201509211300.csv UTC:Sep 21 16:59 /home/filetransfer/incoming/fund_data_201509211400.csv UTC:Sep 21 17:59 /home/filetransfer/incoming/fund_data_201509211500.csv UTC:Sep 21 18:59 /home/filetransfer/incoming/fund_data_201509211600.csv UTC:Sep 21 19:59 /home/filetransfer/incoming/fund_data_201509211700.csv UTC:Sep 21 20:59 /home/filetransfer/incoming/fund_data_201509211800.csv UTC:Sep 21 21:59 /home/filetransfer/incoming/fund_data_201509211900.csv UTC:Sep 21 22:59 /home/filetransfer/incoming/fund_data_201509212000.csv UTC:Sep 21 23:59 /home/filetransfer/incoming/fund_data_201509212100.csv UTC:Sep 22 00:59 /home/filetransfer/incoming/fund_data_201509220700.csv UTC:Sep 22 11:00 /home/filetransfer/incoming/fund_data_201509220800.csv UTC:Sep 22 11:59 /home/filetransfer/incoming/fund_data_201509220900.csv UTC:Sep 22 12:59 /home/filetransfer/incoming/fund_data_201509221000.csv UTC:Sep 22 13:59 /home/filetransfer/incoming/fund_data_201509221100.csv UTC:Sep 22 14:59 /home/filetransfer/incoming/fund_data_201509221200.csv UTC:Sep 22 15:59 /home/filetransfer/incoming/fund_data_201509221300.csv UTC:Sep 22 16:59 /home/filetransfer/incoming/fund_data_201509221400.csv UTC:Sep 22 17:59 /home/filetransfer/incoming/fund_data_201509221500.csv UTC:Sep 22 18:59 /home/filetransfer/incoming/fund_data_201509221600.csv UTC:Sep 22 19:59 /home/filetransfer/incoming/fund_data_201509221700.csv UTC:Sep 22 20:59 /home/filetransfer/incoming/fund_data_201509221800.csv UTC:Sep 22 21:59 /home/filetransfer/incoming/fund_data_201509221900.csv UTC:Sep 22 22:59 /home/filetransfer/incoming/fund_data_201509222000.csv UTC:Sep 22 23:59 /home/filetransfer/incoming/fund_data_201509222100.csv UTC:Sep 23 00:59 /home/filetransfer/incoming/fund_data_201509230700.csv UTC:Sep 23 10:59 /home/filetransfer/incoming/fund_data_201509230800.csv UTC:Sep 23 11:59 /home/filetransfer/incoming/fund_data_201509230900.csv UTC:Sep 23 12:59 /home/filetransfer/incoming/fund_data_201509231000.csv UTC:Sep 23 13:59 /home/filetransfer/incoming/fund_data_201509231100.csv UTC:Sep 23 14:59 /home/filetransfer/incoming/fund_data_201509231200.csv UTC:Sep 23 15:59 /home/filetransfer/incoming/fund_data_201509231300.csv UTC:Sep 23 16:59 /home/filetransfer/incoming/fund_data_201509231400.csv UTC:Sep 23 17:59 /home/filetransfer/incoming/fund_data_201509231500.csv UTC:Sep 23 18:59 /home/filetransfer/incoming/fund_data_201509231600.csv UTC:Sep 23 19:59 /home/filetransfer/incoming/fund_data_201509231700.csv UTC:Sep 23 20:59 /home/filetransfer/incoming/fund_data_201509231800.csv UTC:Sep 23 21:59 /home/filetransfer/incoming/fund_data_201509231900.csv UTC:Sep 23 22:59 /home/filetransfer/incoming/fund_data_201509232000.csv UTC:Sep 23 23:59 /home/filetransfer/incoming/fund_data_201509232100.csv UTC:Sep 24 00:59 /home/filetransfer/incoming/fund_data_201509240700.csv UTC:Sep 24 11:00 /home/filetransfer/incoming/fund_data_201509240800.csv UTC:Sep 24 12:00 /home/filetransfer/incoming/fund_data_201509240900.csv UTC:Sep 24 12:59 /home/filetransfer/incoming/fund_data_201509241000.csv UTC:Sep 24 14:00 /home/filetransfer/incoming/fund_data_201509241100.csv UTC:Sep 24 14:59 /home/filetransfer/incoming/fund_data_201509241200.csv UTC:Sep 24 15:59 /home/filetransfer/incoming/fund_data_201509241300.csv UTC:Sep 24 16:59 /home/filetransfer/incoming/fund_data_201509241400.csv UTC:Sep 24 17:59 /home/filetransfer/incoming/fund_data_201509241500.csv UTC:Sep 24 18:59 /home/filetransfer/incoming/fund_data_201509241600.csv UTC:Sep 24 19:59 /home/filetransfer/incoming/fund_data_201509241700.csv UTC:Sep 24 20:59 /home/filetransfer/incoming/fund_data_201509241900.csv UTC:Sep 24 22:59 /home/filetransfer/incoming/fund_data_201509242000.csv UTC:Sep 24 23:59 /home/filetransfer/incoming/fund_data_201509242100.csv UTC:Sep 25 00:59 /home/filetransfer/incoming/fund_data_201509250700.csv UTC:Sep 25 10:59 /home/filetransfer/incoming/fund_data_201509250800.csv UTC:Sep 25 11:59 /home/filetransfer/incoming/fund_data_201509250900.csv UTC:Sep 25 12:59 /home/filetransfer/incoming/fund_data_201509251000.csv UTC:Sep 25 13:59 /home/filetransfer/incoming/fund_data_201509251100.csv UTC:Sep 25 15:00 /home/filetransfer/incoming/fund_data_201509251200.csv UTC:Sep 25 15:59 /home/filetransfer/incoming/fund_data_201509251300.csv UTC:Sep 25 16:59 /home/filetransfer/incoming/fund_data_201509251400.csv UTC:Sep 25 17:59 /home/filetransfer/incoming/fund_data_201509251500.csv UTC:Sep 25 18:59 /home/filetransfer/incoming/fund_data_201509251600.csv UTC:Sep 25 19:59 /home/filetransfer/incoming/fund_data_201509251700.csv UTC:Sep 25 20:59 /home/filetransfer/incoming/fund_data_201509251800.csv UTC:Sep 25 21:59 /home/filetransfer/incoming/fund_data_201509251900.csv UTC:Sep 25 22:59 /home/filetransfer/incoming/fund_data_201509252000.csv UTC:Sep 25 23:59 /home/filetransfer/incoming/fund_data_201509252100.csv UTC:Sep 26 00:59 /home/filetransfer/incoming/fund_data_201509260700.csv UTC:Sep 26 10:59 /home/filetransfer/incoming/fund_data_201509260800.csv UTC:Sep 26 11:59 /home/filetransfer/incoming/fund_data_201509260900.csv UTC:Sep 26 12:59 /home/filetransfer/incoming/fund_data_201509261000.csv UTC:Sep 26 13:59 /home/filetransfer/incoming/fund_data_201509261100.csv UTC:Sep 26 14:59 /home/filetransfer/incoming/fund_data_201509261200.csv UTC:Sep 26 15:59 /home/filetransfer/incoming/fund_data_201509261300.csv UTC:Sep 26 16:59 /home/filetransfer/incoming/fund_data_201509261400.csv UTC:Sep 26 17:59 /home/filetransfer/incoming/fund_data_201509261500.csv UTC:Sep 26 18:59 /home/filetransfer/incoming/fund_data_201509261600.csv UTC:Sep 26 19:59 /home/filetransfer/incoming/fund_data_201509261700.csv UTC:Sep 26 20:59 /home/filetransfer/incoming/fund_data_201509261800.csv UTC:Sep 26 21:59 /home/filetransfer/incoming/fund_data_201509261900.csv UTC:Sep 26 22:59 /home/filetransfer/incoming/fund_data_201509262000.csv UTC:Sep 26 23:59 /home/filetransfer/incoming/fund_data_201509262100.csv UTC:Sep 27 00:59 /home/filetransfer/incoming/fund_data_201509280700.csv UTC:Sep 28 10:59 /home/filetransfer/incoming/fund_data_201509280800.csv UTC:Sep 28 11:59 /home/filetransfer/incoming/fund_data_201509280900.csv UTC:Sep 28 12:59 /home/filetransfer/incoming/fund_data_201509281000.csv UTC:Sep 28 13:59 /home/filetransfer/incoming/fund_data_201509281100.csv UTC:Sep 28 14:59 /home/filetransfer/incoming/fund_data_201509281200.csv UTC:Sep 28 15:59 /home/filetransfer/incoming/fund_data_201509281300.csv UTC:Sep 28 16:59 /home/filetransfer/incoming/fund_data_201509281400.csv UTC:Sep 28 17:59 /home/filetransfer/incoming/fund_data_201509281500.csv UTC:Sep 28 18:59 /home/filetransfer/incoming/fund_data_201509281600.csv UTC:Sep 28 19:59 /home/filetransfer/incoming/fund_data_201509281800.csv UTC:Sep 28 21:59 /home/filetransfer/incoming/fund_data_201509281900.csv UTC:Sep 28 22:59 /home/filetransfer/incoming/fund_data_201509282000.csv UTC:Sep 28 23:59 /home/filetransfer/incoming/fund_data_201509290700.csv UTC:Sep 29 10:59 /home/filetransfer/incoming/fund_data_201509290800.csv UTC:Sep 29 11:59 /home/filetransfer/incoming/fund_data_201509290900.csv UTC:Sep 29 12:59 /home/filetransfer/incoming/fund_data_201509291000.csv UTC:Sep 29 13:59 /home/filetransfer/incoming/fund_data_201509291100.csv UTC:Sep 29 14:59 /home/filetransfer/incoming/fund_data_201509291200.csv UTC:Sep 29 15:59 /home/filetransfer/incoming/fund_data_201509291300.csv UTC:Sep 29 16:59 /home/filetransfer/incoming/fund_data_201509291400.csv UTC:Sep 29 17:59

**Comment by jacobgodin** [comment]
Hi @kgallagher these are most likely from the 18F system. You may want to double check with them to be sure

**Comment by kgallagher** [comment]
CM has shut this off.
