### ISSUE TITLE
Peace Corps' Cold Fusion Server

### ISSUE THREAD

**Issue by kgallagher** [forumone/peacecorps-site#380]
Jacob, 

Are we still reliant on any way on the Peace Corps server that was  handling the beta.peacecorps.gov -> donate.peacecorps.gov? If not, I want to alert OCIO that they can completely shut that down.

Thanks,
Kelley

**Comment by defbyte** [comment]
once we can safely setup the redirect for `beta.peacecorps.gov` :arrow_forward: `donate.peacecorps.gov` OCIO can pull the plug on the legacy Coldfusion server.

@jacobgodin will be able to confirm when that happens.

**Comment by kgallagher** [comment]
@jacobgodin is the beta.peacecorps.gov :arrow_forward: donate.peacecorps.gov redirect still able to happen today? I'm going to do another status update for PC stakeholders today, but will hold off on sending if there's a chance I can include that news.

**Comment by jacobgodin** [comment]
@kgallagher redirect has been re-implemented. Please feel free to have them decommission when ready.

**Comment by kgallagher** [comment]
Thank you!
