### ISSUE TITLE
Setup CircleCI

### ISSUE THREAD

**Issue by defbyte** [forumone/peacecorps-site#381]
We need to setup [CircleCI](https://circleci.com), and update the CircleCI profile:
https://github.com/Threespot/peacecorps-site/blob/master/docs/developer-guide/getting-started.md#a-note-on-tests

**Comment by defbyte** [comment]
Threespot is investigating setup of CircleCI and what impact that has on our Organization's Third-party access settings.

**Comment by sshami** [comment]
@defbyte I was going to contact you about CircleCi - thanks for getting on this!

**Comment by defbyte** [comment]
@sshami do you know if 18F's CircleCI was a paid plan, or the free tier?

I must speak with the rest of our tech crew here about third-party application access.

**Comment by sshami** [comment]
@defbyte I'm not sure whether it was free or paid - if I had to take a guess I'd say free. It seems like the free CricleCi plan allows 1 concurrent build with 1 container which I believe is sufficient for our purposes. Let me know if you think otherwise.

**Comment by defbyte** [comment]
@sshami CircleCI has been setup

**Comment by sshami** [comment]
@defbyte Awesome, I see it running on your pull request. Thanks!

**Comment by sshami** [comment]
@defbyte Just for clarification - is this something that will automatically be triggered by each pull request or does it have to be triggered manually?

**Comment by defbyte** [comment]
@sshami this should be automatic

**Comment by defbyte** [comment]
@sshami confirmed that circleci gets triggered when one pushes
