### ISSUE TITLE
Donations Documentation

### ISSUE THREAD

**Issue by kgallagher** [forumone/peacecorps-site#384]
18F had setup our Donations documentation on Read The Docs (http://peace-corps-cms.readthedocs.org/). We would like to have the same setup for the new migrated Donations site. Since Threespot owns the repository, will you be able to setup our documentation on Read The Docs?

**Comment by defbyte** [comment]
Hey @sshami do you know if Read The Docs was setup to auto-update when repository code changes?

**Comment by defbyte** [comment]
I started setting up the Read the Docs, but will have to investigate build failures.

Once it builds, it will be accessible here:
http://peace-corps-donations-portal.readthedocs.org/en/latest/

**Comment by sshami** [comment]
@defbyte I would imagine it auto-updated (build again) when docs were changed in the repo. Not 100% sure tho. I personally just accessed the docs directly from the repo when I had to. Also, I wonder if GitHub Wiki can be setup to pull from docs - just a thought.

**Comment by defbyte** [comment]
I'm kind of thinking along the same lines as you @sshami - the docs are totally readable on GitHub (as they are Markdown) and we should explore a different approach

It looks like the Read The Docs integration has been breaking since late March:

<img width="1243" alt="screenshot 2015-09-30 19 08 35" src="https://cloud.githubusercontent.com/assets/338892/10209173/cb0f4f7c-67a6-11e5-8103-39435cef0895.png">

**Comment by sshami** [comment]
Was looking into this and seems like I got a build working off my fork. @defbyte  When you get the chance, could you try rebuilding with "requirements-dev.txt" and install inside virtualenv specified in the advanced settings under Admin. requirements-dev.txt has the mkdoc yml file specified.

My build: http://peace-corps-donations-cms.readthedocs.org/en/latest/

![readdocs-screen](https://cloud.githubusercontent.com/assets/2728077/10231942/affb7208-6853-11e5-9258-10700b2ed26b.png)

**Comment by defbyte** [comment]
woot! I should have tried that @sshami !

`requirements-dev.txt` includes the relevant Python package.

:boom: :book: up and running: http://peace-corps-donations-portal.readthedocs.org/en/latest/

this can be closed once verified by the opener @kgallagher

**Comment by sshami** [comment]
@defbyte great, thanks! the docs should rebuild every night to update with any changes, also if the Github readthedocs webhook/service is working it should update instantly every time something's pushed. @kgallagher we can close this

**Comment by defbyte** [comment]
@sshami the next time a push is invoked, the web hook should be triggered.

If I am clear to merge the 18F references update to the repository, I could test this. (it passes CI)

**Comment by sshami** [comment]
@defbyte sounds good. I think we're good to merge the 18F to Threespot references changes. thanks.

**Comment by defbyte** [comment]
HI @sshami I setup ReadTheDocs through "GitHub Services" - it was way simpler and magical than the webhook route:
http://peace-corps-donations-portal.readthedocs.org/en/latest/

It builds with changes to master

**Comment by sshami** [comment]
@defbyte awesome, thanks
