### ISSUE TITLE
Photos not showing

### ISSUE THREAD

**Issue by kgallagher** [forumone/peacecorps-site#386]
Hey, 
We've noticed that many photos are not appearing within the donations portal. Photos uploaded within the body of the text on fund and project pages are not showing up. A screen shot example is attached. 

Can you please look into this right away?

![image](https://cloud.githubusercontent.com/assets/8482590/10226279/86a6bfda-6834-11e5-83bb-902f4c46d868.png)

cc: @jacobgodin

**Comment by jacobgodin** [comment]
@kgallagher looks like there are images that statically reference the old S3 buckets. @defbyte any ideas for a good solution here?

**Comment by kgallagher** [comment]
Ok, please let us know ASAP. This was brought to our attention by a family who noticed that the photos in their son's memorial fund page weren't showing and contacted a regional director about it.

**Comment by sshami** [comment]
@jacobgodin @defbyte wonder if it will involve a find and replace on all database entries referring to the old S3 bucket (peacecorps-prod-media) to the new (donate-peacecorps-media) ?

**Comment by defbyte** [comment]
@kgallagher please send me the URL of the page so that I can check it out.

@sshami I suspect that there are URIs for assets _in_ the database content.

**Comment by kgallagher** [comment]
From what I can tell it's all project and fund pages that had photos uploaded within the text (not headers). This is just one example: https://donate.peacecorps.gov/donate/project/emergency-management-and-preparedness-on-and-around-mexicoa-s-tallest-peaks/

**Comment by defbyte** [comment]
We will need to run a find and replace query on the database content for these fields to change:

`peacecorps-prod-media`
to:
`donate-peacecorps-media`

this must be content that was created with that WYSIWYG tool.

**Comment by sshami** [comment]
@defbyte yup WYSIWYG seems to be used to upload picture attachments. @kgallagher will provide you with access to the donations CMS so you can take a look as well

**Comment by kgallagher** [comment]
Just sent via email.

**Comment by defbyte** [comment]
confirmed that these content fields are storing full URIs to assets (Sir Trevor enabled fields)

We are working SQL to find/replace these values.

**Comment by defbyte** [comment]
@kgallagher @sshami we have run update queries to find and replace the problem portion of asset URIs, and images have returned. 

SQL for reference:

``` sql
update peacecorps_campaign set description = replace(description, 'https://peacecorps-prod-media.s3.amazonaws.com', 'https://donate-peacecorps-media.s3.amazonaws.com');

update peacecorps_project set description = replace(description, 'https://peacecorps-prod-media.s3.amazonaws.com', 'https://donate-peacecorps-media.s3.amazonaws.com');

update peacecorps_faq set answer = replace(answer, 'https://peacecorps-prod-media.s3.amazonaws.com', 'https://donate-peacecorps-media.s3.amazonaws.com');

```

**Comment by kgallagher** [comment]
Thank you for addressing this quickly. Super appreciated.
