### ISSUE TITLE
Local Development Environment Setup Missing Libs Needed

### ISSUE THREAD

**Issue by defbyte** [forumone/peacecorps-site#389]
Local setup running `vagrant up` will fail because these two libraries are not installed during provisioning:
- `libmemcached-dev`
- `libjpeg-dev`

**Comment by sshami** [comment]
Thanks Chris, issue #388 addresses libjpeg requirements as well. I was wondering if it may be beneficial to pin all these libraries to specific versions to avoid having to update/add new libraries if dependencies change with newer versions.

**Comment by defbyte** [comment]
@sshami yes, I would recommend we evaluate the items in the Django app's requirements files, and pin what we can (if not all) to at least a major/minor version combo/range.
