### ISSUE TITLE
Three hyphens = bad neighborhood SEO signal

### ISSUE THREAD

**Issue by lfrancis** [forumone/peacecorps-site#405]
Chris, assume this goes away in production but found it an interesting new item to be aware of.

Some search engines may penalize links to bad neighborhoods. Three or more hyphens in the domain name are used as a bad neighborhood indicator by search engines. Make sure these links are marked with REL='NOFOLLOW' to avoid affecting your Google ranking. Google Bing  Options 

 Link: https://stage-donate-peacecorps-static.s3.amazonaws.com/peacecorps/css/compiled/donation.min.css
https://stage-donate.peacecorps.gov/donate/projects-funds/  22 26 28

**Comment by defbyte** [comment]
@lfrancis even URIs to assets the page requests?

**Comment by lfrancis** [comment]
yup. Who knows what lives in that bad neighborhood.

**Comment by defbyte** [comment]
this should go away in production as the domain is `donate.peacecorps.gov`

**Comment by lfrancis** [comment]
Cool, closing.
