### ISSUE TITLE
Expanded 

### ISSUE THREAD

**Issue by lfrancis** [forumone/peacecorps-site#412]
https://stage-donate.peacecorps.gov/donate/projects-funds/#volunteer?project=collapsible-project-1706

If you follow this link and look for the expanded item, you see an extra small circle icon that disappears if you close the view and then re-open it.

![circle_dupe](https://cloud.githubusercontent.com/assets/6942589/11190738/502270a8-8c65-11e5-900f-c0011d0341ca.png)

**Comment by defbyte** [comment]
ah this was a fun one to fix - ready for review on the Staging site

**Comment by lfrancis** [comment]
Confirmed addressed
