### ISSUE TITLE
Back button behavior on filtered lists

### ISSUE THREAD

**Issue by bwilliams3** [forumone/peacecorps-site#414]
In Chrome/Firefox/IE:
1. Load https://stage-donate.peacecorps.gov/donate/projects-funds/
2. Click any filter or sequence of filters
3. Click Back button
4. Sent to homepage https://stage-donate.peacecorps.gov/donate/

This works as expected in Safari, where at Step 4 you are sent to the initial filter page at https://stage-donate.peacecorps.gov/donate/projects-funds/

**Comment by lizott** [comment]
@defbyte can you take a look?

**Comment by sshami** [comment]
@defbyte FYI, I tested this on an older version of Chrome I had on my laptop (42.0) and the back button behavior worked fine. I'm updating my Chrome now to see if it stops functioning on the latest version.

**Comment by sshami** [comment]
Stopped working when I updated to the latest version of Chrome (46.0).

**Comment by defbyte** [comment]
thanks for the info @sshami I'll be checking this out.

We're using History pushState and popState to make entries in the browser's history

**Comment by defbyte** [comment]
This is ready for review on the Staging site

**Comment by bwilliams3** [comment]
[Re-posting this comment to correct Issue thread]

@defbyte @sshami 

Testing for Issue #414 in Chrome/FF/Safari:
- This is working very well for common use cases -- navigating between category filters and into/out of individual project pages
- One exception is "backing out" of an expanded project view, i.e.:
  1. Go to https://stage-donate.peacecorps.gov/donate/projects-funds/#issue
  2. Click Agriculture https://stage-donate.peacecorps.gov/donate/projects-funds/#issue?subSection=issue-9
  3. Click Senegal https://stage-donate.peacecorps.gov/donate/projects-funds/#issue?subSection=issue-9&project=collapsible-project-1570
  4. Click Back button; the URL in the browser bar correctly updates to the previous step, but Senegal remains expanded, which makes it appear to the user as though the Back button did nothing
  5. Similarly, if you click Senegal, then Botswana, then "Back" to Senegal, Botswana remains expanded even though the URL updates correctly to Senegal.

**Comment by defbyte** [comment]
Thanks for the detailed replication steps @bwilliams3 this is incredibly helpful to diagnose the issue (which i am doing so now).

**Comment by defbyte** [comment]
Hi @bwilliams3 this issue is ready for review in the Staging environment.

_please clear your cache before testing_ I noticed the .js was cached for me initially.

https://stage-donate.peacecorps.gov/donate/projects-funds/

**Comment by bwilliams3** [comment]
@defbyte Works great, thanks!
