### ISSUE TITLE
Project detail view disabled in IE

### ISSUE THREAD

**Issue by bwilliams3** [forumone/peacecorps-site#415]
This functionality works on the production site but has broken on staging:
1. Go to Projects and Funds https://stage-donate.peacecorps.gov/donate/projects-funds/
2. Expand any filter area and click on a specific fund (i.e., Education > Cameroon)
3. The fund should then expand to a detailed view, but in IE this no longer works.

**Comment by sshami** [comment]
FYI, we tested on IE 9.

**Comment by defbyte** [comment]
@sshami and @bwilliams3 when we QA'd, we tested IE10 and up

**Comment by bwilliams3** [comment]
Yeah, Peace Corps HQ is still on IE9 unfortunately, so if it doesn’t work we’ll hear about it from staff.

**Comment by defbyte** [comment]
@bwilliams3 @sshami thanks for the feedback, I will investigate and include IE9 in the testing rotation!

**Comment by defbyte** [comment]
what version of Windows were you all running IE9? @sshami @bwilliams3

**Comment by defbyte** [comment]
ah ok - IE9 doesn't support session history management: http://caniuse.com/#feat=history and throws an error that stops script execution.

gotta add some feature detection to account for this.

**Comment by defbyte** [comment]
hello @bwilliams3 this is ready for review on the Staging site.

Please see the note above about IE9 not supporting session history management. This feature won't be available on IE9 and below. IE10 and up should be good. Am using feature detection so the JavaScript doesn't :bomb:

**Comment by bwilliams3** [comment]
Confirmed works well -- thanks!
